blank_issues_enabled: true
contact_links:
  - name: Download and setup Inhouse Photos
    url: https://fotos.miguelcoxcaballero.com/descargas/
    about: Download the Android app or Windows server manager and follow the setup steps.
